app:
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  access-type: SQL
  batch-size: 100

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/link_tracker_db
    username: nifreebie
    password: nis150905
  config:
    import: optional:file:.env[.properties]

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
