/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package backend.academy.scrapper.openapi.src.main.java.com.baeldung.openapi.api;

import backend.academy.scrapper.model.dto.request.AddLinkRequest;
import backend.academy.scrapper.model.dto.request.RemoveLinkRequest;
import backend.academy.scrapper.model.dto.response.ApiErrorResponse;
import backend.academy.scrapper.model.dto.response.LinkResponse;
import backend.academy.scrapper.model.dto.response.ListLinksResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-04-23T13:12:14.088362900+03:00[Europe/Moscow]",
        comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "links", description = "the links API")
public interface LinksApi {

    default LinksApiDelegate getDelegate() {
        return new LinksApiDelegate() {};
    }

    /**
     * DELETE /links : Убрать отслеживание ссылки
     *
     * @param tgChatId (required)
     * @param removeLinkRequest (required)
     * @return Ссылка успешно убрана (status code 200) or Некорректные параметры запроса (status code 400) or Ссылка не
     *     найдена (status code 404)
     */
    @Operation(
            operationId = "linksDelete",
            summary = "Убрать отслеживание ссылки",
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "Ссылка успешно убрана",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = LinkResponse.class))
                        }),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        }),
                @ApiResponse(
                        responseCode = "404",
                        description = "Ссылка не найдена",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/links",
            produces = {"application/json"},
            consumes = {"application/json"})
    default ResponseEntity<?> linksDelete(
            @NotNull
                    @Parameter(name = "Tg-Chat-Id", description = "", required = true, in = ParameterIn.HEADER)
                    @RequestHeader(value = "Tg-Chat-Id", required = true)
                    Long tgChatId,
            @Parameter(name = "RemoveLinkRequest", description = "", required = true) @Valid @RequestBody
                    RemoveLinkRequest removeLinkRequest) {
        return getDelegate().linksDelete(tgChatId, removeLinkRequest);
    }

    /**
     * GET /links : Получить все отслеживаемые ссылки
     *
     * @param tgChatId (required)
     * @return Ссылки успешно получены (status code 200) or Некорректные параметры запроса (status code 400)
     */
    @Operation(
            operationId = "linksGet",
            summary = "Получить все отслеживаемые ссылки",
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "Ссылки успешно получены",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ListLinksResponse.class))
                        }),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/links",
            produces = {"application/json"})
    default ResponseEntity<?> linksGet(
            @NotNull
                    @Parameter(name = "Tg-Chat-Id", description = "", required = true, in = ParameterIn.HEADER)
                    @RequestHeader(value = "Tg-Chat-Id", required = true)
                    Long tgChatId) {
        return getDelegate().linksGet(tgChatId);
    }

    /**
     * POST /links : Добавить отслеживание ссылки
     *
     * @param tgChatId (required)
     * @param addLinkRequest (required)
     * @return Ссылка успешно добавлена (status code 200) or Некорректные параметры запроса (status code 400)
     */
    @Operation(
            operationId = "linksPost",
            summary = "Добавить отслеживание ссылки",
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "Ссылка успешно добавлена",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = LinkResponse.class))
                        }),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/links",
            produces = {"application/json"},
            consumes = {"application/json"})
    default ResponseEntity<?> linksPost(
            @NotNull
                    @Parameter(name = "Tg-Chat-Id", description = "", required = true, in = ParameterIn.HEADER)
                    @RequestHeader(value = "Tg-Chat-Id", required = true)
                    Long tgChatId,
            @Parameter(name = "AddLinkRequest", description = "", required = true) @Valid @RequestBody
                    AddLinkRequest addLinkRequest) {
        return getDelegate().linksPost(tgChatId, addLinkRequest);
    }
}
