/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package backend.academy.scrapper.openapi.src.main.java.com.baeldung.openapi.api;

import backend.academy.scrapper.model.dto.response.ApiErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-04-23T13:12:14.088362900+03:00[Europe/Moscow]",
        comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "tg-chat", description = "the tg-chat API")
public interface TgChatApi {

    default TgChatApiDelegate getDelegate() {
        return new TgChatApiDelegate() {};
    }

    /**
     * DELETE /tg-chat/{id} : Удалить чат
     *
     * @param id (required)
     * @return Чат успешно удалён (status code 200) or Некорректные параметры запроса (status code 400) or Чат не
     *     существует (status code 404)
     */
    @Operation(
            operationId = "tgChatIdDelete",
            summary = "Удалить чат",
            responses = {
                @ApiResponse(responseCode = "200", description = "Чат успешно удалён"),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        }),
                @ApiResponse(
                        responseCode = "404",
                        description = "Чат не существует",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/tg-chat/{id}",
            produces = {"application/json"})
    default ResponseEntity<?> tgChatIdDelete(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id")
                    Long id) {
        return getDelegate().tgChatIdDelete(id);
    }

    /**
     * POST /tg-chat/{id} : Зарегистрировать чат
     *
     * @param id (required)
     * @return Чат зарегистрирован (status code 200) or Некорректные параметры запроса (status code 400)
     */
    @Operation(
            operationId = "tgChatIdPost",
            summary = "Зарегистрировать чат",
            responses = {
                @ApiResponse(responseCode = "200", description = "Чат зарегистрирован"),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/tg-chat/{id}",
            produces = {"application/json"})
    default ResponseEntity<?> tgChatIdPost(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id")
                    Long id) {
        return getDelegate().tgChatIdPost(id);
    }
}
