package backend.academy.bot.model;

public enum UserState {
    DEFAULT,
    AWAITING_TRACK_URL,
    AWAITING_UNTRACK_URL,
    AWAITING_TAGS,
    AWAITING_FILTERS,
    AWAITING_TAG_NAME,
    AWAITING_ADD_TAGS_URL,
    AWAITING_ADD_TAGS_NAME,
    AWAITING_REMOVE_TAGS_URL,
    AWAITING_REMOVE_TAGS_NAME,
}
