/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package backend.academy.bot.openapi.src.main.java.com.baeldung.openapi.api;

import backend.academy.bot.model.dto.request.LinkUpdateRequest;
import backend.academy.bot.model.dto.response.ApiErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-04-23T11:51:06.950796200Z[UTC]",
        comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "updates", description = "the updates API")
public interface UpdatesApi {

    default UpdatesApiDelegate getDelegate() {
        return new UpdatesApiDelegate() {};
    }

    /**
     * POST /updates : Отправить обновление
     *
     * @param linkUpdate (required)
     * @return Обновление обработано (status code 200) or Некорректные параметры запроса (status code 400)
     */
    @Operation(
            operationId = "updatesPost",
            summary = "Отправить обновление",
            responses = {
                @ApiResponse(responseCode = "200", description = "Обновление обработано"),
                @ApiResponse(
                        responseCode = "400",
                        description = "Некорректные параметры запроса",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = ApiErrorResponse.class))
                        })
            })
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/updates",
            produces = {"application/json"},
            consumes = {"application/json"})
    default ResponseEntity<String> updatesPost(
            @Parameter(name = "LinkUpdate", description = "", required = true) @Valid @RequestBody
                    LinkUpdateRequest linkUpdate) {
        return getDelegate().updatesPost(linkUpdate);
    }
}
